App:
  background: '#FDFDFD'
  foreground: '#333333'
  border: '#CCCCCC'
Navbar:
  background: '#333333'
  foreground: '#FDFDFD'
Entry:
  background: '#FFFFFF'
  foreground: '#333333'
  placeholder: '#999999'
  border: '#CCCCCC'
  outline: '#1ac6ff'
Button:
  cloud:
    background: '#f5f5f5'
    foreground: '#212121'
    on_hover: '#e0e0e0'
    disabled_bg: '#eeeeee'
    disabled_fg: '#9e9e9e'
  info:
    background: '#33b5e5'
    foreground: '#fafafa'
    on_hover: '#0099CC'
    disabled_bg: '#64b5f6'
    disabled_fg: '#e0e0e0'
  primary:
    background: '#4285F4'
    foreground: '#fafafa'
    on_hover: '#0d47a1'
    disabled_bg: '#82b1ff'
    disabled_fg: '#e0e0e0'
  danger:
    background: '#ff4444'
    foreground: '#fafafa'
    on_hover: '#CC0000'
    disabled_bg: '#ff8a80'
    disabled_fg: '#e0e0e0'
  warning:
    background: '#ffbb33'
    foreground: '#fafafa'
    on_hover: '#FF8800'
    disabled_bg: '#f0f4c3'
    disabled_fg: '#e0e0e0'
  success:
    background: '#00C851'
    foreground: '#fafafa'
    on_hover: '#007E33'
    disabled_bg: '#a5d6a7'
    disabled_fg: '#e0e0e0'
  elegant:
    background: '#2E2E2E'
    foreground: '#fafafa'
    on_hover: '#212121'
    disabled_bg: '#757575'
    disabled_fg: '#e0e0e0'
  default:
    background: '#2BBBAD'
    foreground: '#fafafa'
    on_hover: '#00695c'
    disabled_bg: '#80cbc4'
    disabled_fg: '#e0e0e0'